### ISSUE TITLE
why do u choose EhCache

### ISSUE THREAD

**Issue by HelloTo4x** [ecnice/flow#13]
Hi, why do u choose EhCache for caching instead of other caches like Caffeine, redis... because i see Cafeine workes higher perfomance than Ehcache

**Comment by ecnice** [comment]
对不起，我英文不是很好，但是我还是能看懂你说的意思，我之所以采用ehcache是因为在这个世界上不是所有的项目都很大，有很多项目都是单体的很小，这样子我采用ehcache更加简单方便，
其实我们做项目选择最合适的技术才是最为重要的，而不是最先进的技术，如果你是一个大型项目，当然redis是首选，当然了，还是看我们的使用用户，一般5000人的公司，这种内部系统，我们采用ehcache是没有任何问题的。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecnice/flow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 上午9:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ecnice/flow] why do u choose EhCache (Issue #13)





 
Hi, why do u choose EhCache for caching instead of other caches like Caffeine, redis... because i see Cafeine workes higher perfomance than Ehcache

**Comment by HelloTo4x** [comment]
which data are u caching ?

**Comment by ecnice** [comment]
看一下这个文件
flow-ehcache.xml




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ecnice/flow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ecnice/flow] why do u choose EhCache (Issue #13)





 
which data are u caching ?
